[package]
name = "rsapcupsdexporter"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4.12.1", default-features = false, features = ["compress-gzip", "macros"] }
dashmap = "6.2.1"
env_logger = "0.11.8"
log = "0.4.29"
prometheus = { version = "0.14", features = ["process"] }
tokio = { version = "1", default-features = false, features = ["time"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
similar_names = "allow"
missing_errors_doc = "allow"

[profile.release]
opt-level = "z"     # Optimize for size
lto = true          # Link Time Optimization
codegen-units = 1   # Better optimization
strip = true        # Strip symbols
panic = "abort"     # Smaller panic handler
overflow-checks = false  # Disable overflow checks in release
