apiVersion: v2
name: rs-apcupsd-exporter
description: APC UPSD Prometheus Exporter
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/TymekV/rsapcupsdexporter
sources:
  - https://github.com/TymekV/rsapcupsdexporter
